### ISSUE TITLE
Extension cd failed during setup. This might have left the registry in a bad state.

### ISSUE THREAD

**Issue by mutlucan96** [asartori/mopidy-cd#21]
Runinnig this on Fedora 38 and it doesn't work. Fresh install mopidy and mopidy-cd, no additional config.
```
ERROR    2023-08-15 21:08:53,093 [12362:MainThread] mopidy.__main__
  Extension cd failed during setup. This might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.11/site-packages/mopidy_cd/__init__.py", line 22, in setup
    from .backend import CdBackend
  File "/usr/local/lib/python3.11/site-packages/mopidy_cd/backend.py", line 11, in <module>
    from .cdrom import CD_PROTOCOL, UNKNOWN_DISC, CdRom
  File "/usr/local/lib/python3.11/site-packages/mopidy_cd/cdrom.py", line 8, in <module>
    from collections import Mapping, namedtuple
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)

```

**Comment by Fubukimaru** [comment]
This issue is caused by a change of the `Mapping` object inside the `collections` package. I have opened a pull request to fix this.

Meanwhile you con use my fork: https://github.com/Fubukimaru/mopidy-cd
